name: GitHub Actions Demo
on:
  create:
    tags:
jobs:
  cd:
    # Only run this job if the "ci" job passes
    #needs: ci
    # Only run this job on creating a new tag
    #if: github.event_name == 'create' && github.ref == 'refs/tags/*'
    # Step 1. Set up operating system
    runs-on: ubuntu-latest
    steps:
    # Step 2. Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Step 3. Check-out repository so we can access its contents
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 6.
    #- name: create tag
      #run: |
          #git tag -a v0.0.1 -m "My first release."
          #git push origin v0.0.1
    # Step 5.
    - name: increment version release
      run: python3 -m pip install poetry
    - name: 2
      run: | 
        python3 -m poetry version $(git tag | sed -e 's/^v//')
    - name: 3
      run: git add pyproject.toml
    - name: 4
      run: git add pyproject.toml
    - name: 5
      run: git commit -m "Updating the release version in pyproject.toml"
    - name: 6
      run: git tag -f $(git tag)
    - name: 7
      run: git push origin $(git tag)
