name: GitHub Actions Demo
on:
  create:
    tags:
jobs:
  cd:
    # Only run this job on creating a new tag
    if: github.event_name == 'create' && github.ref == 'refs/tags/git tag --list 'v-*''
    # Step 1. Set up operating system
    runs-on: ubuntu-latest
    steps:
    # Step 2. Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Step 3. Check-out repository so we can access its contents
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 6.
    #- name: create tag
      #run: |
          #git tag -a v0.0.1 -m "My first release."
          #git push origin v0.0.1
    # Step 5.
    - name: Install poetry
      run: python3 -m pip install poetry
    - name: Update pyproject.toml version from latest tag
      run: poetry version $(git describe --tags --abbrev=0 | sed -e 's/^v//')
    - name: Tell git who we are
      run: |
          git config --global user.email "none@none.com"
          git config --global user.name "Auto-version-incrementer"
    - name: Commit auto-incrementer changes to existing tag
      run: |
        git add pyproject.toml
        git commit -m "Updating the release version in pyproject.toml"
        git tag -f $(git describe --tags --abbrev=0)
    - name: Push tag changes back to origin
      run: git push -f origin $(git describe --tags --abbrev=0)
